services:
  agent:
    build: .
    container_name: docker-monitor-agent
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "${AGENT_PORT:-8080}:8080"
    environment:
      - AGENT_TOKEN=${AGENT_TOKEN}
      - DOCKER_SOCKET=/var/run/docker.sock
      - HOST=0.0.0.0
      - PORT=8080
    user: "0:0"  # Запуск от root для доступа к Docker socket
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - agent-network

networks:
  agent-network:
    driver: bridge 